services:
  db:
    image: postgres:15
    restart: always
    container_name: investmenttracker-db-1 
    environment:
      POSTGRES_DB: investtrack
      POSTGRES_USER: investuser
      POSTGRES_PASSWORD: investpass
      POSTGRES_HOST_AUTH_METHOD: md5
    ports:
      - "5433:5432" 
    volumes:
      - investmenttracker_pgdata:/var/lib/postgresql/data 

volumes:
  investmenttracker_pgdata: 