# version: '3.8' # Can be removed
services:
  db:
    image: postgres:15
    restart: always
    environment:
      POSTGRES_DB: investtrack
      POSTGRES_USER: investuser
      POSTGRES_PASSWORD: investpass 
      POSTGRES_HOST_AUTH_METHOD: md5
    ports:
      - "5433:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
volumes:
  pgdata: